### PR TITLE
CJHouser: d01

### PR DESCRIPTION
**Pull request by CJHouser**

### CODE REVIEW

**Comment by OscarLuu** [comment]
👀 Those commits though

**Review by OscarLuu — COMMENTED** [review]
@CJHouser Do we want to keep the input files?

**Comment by CJHouser** [comment]
> @CJHouser Do we want to keep the input files?

Yeah, keep them. I believe we each have different inputs.

**Review by OscarLuu — APPROVED** [review]
👍 LGTM

**Pull request merged**
